version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - AUTH_SECRET=i9b42KOxlDFED4HLtvhTHKpoZJoqEzKCIjqDZ7y/0ps=
      - API_BASE_URL=https://springboot-lms-latest.onrender.com
      - AUTH_TRUST_HOST=true
    volumes:
      - .:/app
    command: npm start
